language: cpp
sudo: false

branches:
  except:
    - gh-pages

env:
  global:
    - GH_REPO: github.com/codeplaysoftware/visioncpp.git

addons:
  apt:
    packages:
      - doxygen
      - graphviz
before_script:
  - chmod +x ./scripts/travis_build_docs.sh
  - chmod +x ./scripts/travis_deploy_docs.sh

script:
  - 'if [ "$TRAVIS_REPO_SLUG" = "codeplaysoftware/visioncpp" ] && [ "$TRAVIS_BRANCH" = "master" ]; then bash ./scripts/travis_build_docs.sh; fi'

after_success:
  - 'if [ "$TRAVIS_REPO_SLUG" = "codeplaysoftware/visioncpp" ] && [ "$TRAVIS_BRANCH" = "master" ]; then bash ./scripts/travis_deploy_docs.sh; fi'
