VisionCpp: visioncpp::internal::tools Namespace Reference
visioncpp::internal::tools Namespace Reference
Internal tools scope.
Namespaces
tuple
Contains standard layout tuple implementation.
Classes
struct Convertor
This struct is used to convert the provide struct to flot4, uint4, int4 memory.
struct Convertor< char >
specialisation of the Convertor when the output is char
struct Convertor< cl::sycl::float4 >
Specialisation of Convertor when the output is float4.
struct Convertor< cl::sycl::int4 >
specialisation of Convertor when the output is int4
struct Convertor< cl::sycl::uint4 >
specialisation of the Convertor when the output is uint4
struct Convertor< float >
specialisation of the Convertor when the output is float
struct Convertor< int >
specialisation of the Convertor when the output is int
struct Convertor< short >
specialisation of the Convertor when the output is short
struct Convertor< unsigned char >
specialisation of the Convertor when the output is unsigned char
struct Convertor< unsigned int >
specialisation of the Convertor when the output is unsigned int
struct Convertor< unsigned short >
specialisation of the Convertor when the output is unsigned short
struct Convertor< visioncpp::pixel::F32C3 >
specialisation of the Convertor when the output is F32C3
struct Convertor< visioncpp::pixel::F32C4 >
specialisation of the Convertor when the output is F32C4
struct Convertor< visioncpp::pixel::U8C3 >
specialisation of the Convertor when the output is U8C3
struct Convertor< visioncpp::pixel::U8C4 >
specialisation of the Convertor when the output is U8C4
struct IfConst
struct IfConst< false, X, Y >
specialisation of the IfConst when the condition is false
struct IfNode
This struct is used to determine whether or not an expression node is a leafNode template parameters.
struct IfNode< LeafNode< Nested, LVL > >
specialisation of the IfNode when the node is leafNode
struct RemoveAll
These methods are used to remove all the & const and * from a type. template parameters.
struct RemoveAll< const T & >
specialisation of RemoveAll when the type contains const and &
struct RemoveAll< const T * >
specialisation of RemoveAll when the type contains const and *
struct RemoveAll< const T >
specialisation of RemoveAll when the type contains const
struct RemoveAll< T & >
specialisation of RemoveAll when the type contains &
struct RemoveAll< T * >
specialisation of RemoveAll when the type contains *
struct RemoveAll< T const volatile >
specialisation of RemoveAll when the type contains const volatile
struct RemoveAll< T volatile >
specialisation of RemoveAll when the type contains volatile
struct StaticIf
It is used to select either of the input type based the Conds template parameters.
struct StaticIf< false, T1, T2 >
specialisation of the StaticIf when the condition is false
Functions
template<typename T1 , typename T2 >
T1 convert (T2 x)
function convert
template<typename T >
double get_elapse_time (T begin, T end)
function get_elapse_time
std::chrono::high_resolution_clock::time_point get_current_time ()
function get_current_time
Detailed Description
Internal tools scope.
Function Documentation
convert()
template<typename T1 , typename T2 > T1 visioncpp::internal::tools::convert (T2 x) inline
function convert
template deduction for Convertor struct template parameters
Template Parameters
T1 the output type
T2 the input type function parameters
Parameters
x the input pixel
Returns
T1
Definition at line 558 of file convert.hpp.
References visioncpp::internal::tools::Convertor< T >::convert().
Referenced by visioncpp::internal::EvalExpr< RDCN< C_OP, RHS, Cols, Rows, LfType, LVL >, Loc, Params... >::eval_global_neighbour(), visioncpp::internal::EvalExpr< RDCN< C_OP, RHS, Cols, Rows, LfType, LVL >, Loc, Params... >::eval_neighbour(), visioncpp::internal::EvalExpr< StnNoFilt< C_OP, Halo_T, Halo_L, Halo_B, Halo_R, RHS, Cols, Rows, LfType, LVL >, Loc, Params... >::eval_neighbour(), visioncpp::internal::EvalExpr< StnFilt< C_OP, Halo_T, Halo_L, Halo_B, Halo_R, LHS, RHS, Cols, Rows, LfType, LVL >, Loc, Params... >::eval_neighbour(), visioncpp::internal::EvalExpr< RUnOP< UN_OP, Nested, Cols, Rows, LfType, LVL >, Loc, Params... >::eval_neighbour(), visioncpp::internal::EvalExpr< RBiOP< BI_OP, LHS, RHS, Cols, Rows, LfType, LVL >, Loc, Params... >::eval_neighbour(), visioncpp::internal::EvalExpr< Assign< LHS, RHS, Cols, Rows, LfType, LVL >, Loc, Params... >::eval_neighbour(), and visioncpp::internal::Fill< LeafNode< PlaceHolder< Memory_Type, N, Cols, Rows, Sc >, LVL >, Loc, Params... >::fill_neighbour().
get_current_time()
std::chrono::high_resolution_clock::time_point visioncpp::internal::tools::get_current_time ()
function get_current_time
getting the current time from the system using chrono
Returns
std::chrono::high_resolution_clock::time_point
Definition at line 47 of file time.hpp.
get_elapse_time()
template<typename T > double visioncpp::internal::tools::get_elapse_time (T begin, T end)
function get_elapse_time
it is used to calculate the time period in second. template parameters
Template Parameters
T : the type of the time from chrono function parameters
Parameters
begin : start of the time
end : end of the time returns a double
Definition at line 40 of file time.hpp.