VisionCpp: visioncpp::internal::LocalOutput< PointOp, IsRoot, LC, LR, Expr > Struct Template Reference
visioncpp::internal::LocalOutput< PointOp, IsRoot, LC, LR, Expr > Struct Template Reference
LocalOutput:Local output is used for neighbour operation in order to create a local memory for the output of non-terminal nodes in the expression tree when the NeighbourOP is used.
#include <expr_convertor.hpp>
Static Public Member Functions
static decltype(tools::tuple::make_tuple()) getTuple (cl::sycl::handler &cgh)
getTuple function is used to create and wrap local memory into a tuple
Static Public Attributes
static constexpr size_t Out_LC = LC
static constexpr size_t Out_LR = LR
Detailed Description
template<bool PointOp, size_t IsRoot, size_t LC, size_t LR, typename Expr>
struct visioncpp::internal::LocalOutput< PointOp, IsRoot, LC, LR, Expr >
LocalOutput:Local output is used for neighbour operation in order to create a local memory for the output of non-terminal nodes in the expression tree when the NeighbourOP is used.
LocalOutput accessor.
The local output does nothing when the operation type is point operation. If it is called when the whole expression tree is point op or global op no local memory will be created. When the combination of point op and NeighbourOP is used we consider the expression tree as a NeighbourOP expression tree and generate a set of local memory. template parameters:
Template Parameters
PointOp determines whether or not the overall expression tree is pointOp
IsRoot determines whether or not a node is a root node.
LC determines the column size of the local memory
LR determines the row size of the local memory
Expr determines the type of the expression
Definition at line 52 of file expr_convertor.hpp.
Member Function Documentation
getTuple()
template<bool PointOp, size_t IsRoot, size_t LC, size_t LR, typename Expr > static decltype(tools::tuple::make_tuple()) visioncpp::internal::LocalOutput< PointOp, IsRoot, LC, LR, Expr >::getTuple (cl::sycl::handler & cgh) inline static
getTuple function is used to create and wrap local memory into a tuple
Parameters
cgh : sycl command group handler.
Definition at line 72 of file local_output.hpp.
References visioncpp::internal::tools::tuple::make_tuple().
Referenced by visioncpp::internal::LocalOutput< false, IsRoot, LC, LR, RUnOP< OP, RHSExpr, Cols, Rows, LeafType, LVL > >::getTuple(), visioncpp::internal::LocalOutput< false, IsRoot, LC, LR, RBiOP< OP, LHSExpr, RHSExpr, Cols, Rows, LeafType, LVL > >::getTuple(), visioncpp::internal::LocalOutput< false, IsRoot, LC, LR, StnFilt< OP, Halo_T, Halo_L, Halo_B, Halo_R, LHSExpr, RHSExpr, Cols, Rows, LeafType, LVL > >::getTuple(), visioncpp::internal::LocalOutput< false, IsRoot, LC, LR, StnNoFilt< OP, Halo_T, Halo_L, Halo_B, Halo_R, RHSExpr, Cols, Rows, LeafType, LVL > >::getTuple(), visioncpp::internal::LocalOutput< false, IsRoot, LC, LR, RDCN< OP, RHSExpr, Cols, Rows, LeafType, LVL > >::getTuple(), visioncpp::internal::LocalOutput< false, IsRoot, LC, LR, ParallelCopy< LHSExpr, RHSExpr, Cols, Rows, OffsetColIn, OffsetRowIn, OffsetColOut, OffsetRowOut, LeafType, LVL > >::getTuple(), and visioncpp::internal::LocalOutput< false, IsRoot, LC, LR, Assign< LHSExpr, RHSExpr, Cols, Rows, LeafType, LVL > >::getTuple().
Member Data Documentation
Out_LC
template<bool PointOp, size_t IsRoot, size_t LC, size_t LR, typename Expr > constexpr size_t visioncpp::internal::LocalOutput< PointOp, IsRoot, LC, LR, Expr >::Out_LC = LC static constexpr
Definition at line 67 of file local_output.hpp.
Referenced by visioncpp::internal::LocalOutput< false, IsRoot, LC, LR, RUnOP< OP, RHSExpr, Cols, Rows, LeafType, LVL > >::getTuple(), visioncpp::internal::LocalOutput< false, IsRoot, LC, LR, RBiOP< OP, LHSExpr, RHSExpr, Cols, Rows, LeafType, LVL > >::getTuple(), visioncpp::internal::LocalOutput< false, IsRoot, LC, LR, StnFilt< OP, Halo_T, Halo_L, Halo_B, Halo_R, LHSExpr, RHSExpr, Cols, Rows, LeafType, LVL > >::getTuple(), visioncpp::internal::LocalOutput< false, IsRoot, LC, LR, StnNoFilt< OP, Halo_T, Halo_L, Halo_B, Halo_R, RHSExpr, Cols, Rows, LeafType, LVL > >::getTuple(), and visioncpp::internal::LocalOutput< false, IsRoot, LC, LR, RDCN< OP, RHSExpr, Cols, Rows, LeafType, LVL > >::getTuple().
Out_LR
template<bool PointOp, size_t IsRoot, size_t LC, size_t LR, typename Expr > constexpr size_t visioncpp::internal::LocalOutput< PointOp, IsRoot, LC, LR, Expr >::Out_LR = LR static constexpr
Definition at line 68 of file local_output.hpp.
Referenced by visioncpp::internal::LocalOutput< false, IsRoot, LC, LR, RUnOP< OP, RHSExpr, Cols, Rows, LeafType, LVL > >::getTuple(), visioncpp::internal::LocalOutput< false, IsRoot, LC, LR, RBiOP< OP, LHSExpr, RHSExpr, Cols, Rows, LeafType, LVL > >::getTuple(), visioncpp::internal::LocalOutput< false, IsRoot, LC, LR, StnFilt< OP, Halo_T, Halo_L, Halo_B, Halo_R, LHSExpr, RHSExpr, Cols, Rows, LeafType, LVL > >::getTuple(), visioncpp::internal::LocalOutput< false, IsRoot, LC, LR, StnNoFilt< OP, Halo_T, Halo_L, Halo_B, Halo_R, RHSExpr, Cols, Rows, LeafType, LVL > >::getTuple(), and visioncpp::internal::LocalOutput< false, IsRoot, LC, LR, RDCN< OP, RHSExpr, Cols, Rows, LeafType, LVL > >::getTuple().
The documentation for this struct was generated from the following files:
expr_convertor.hpp
local_output.hpp