VisionCpp: visioncpp::internal::EvalExpr< RDCN< C_OP, RHS, Cols, Rows, LfType, LVL >, Loc, Params...> Struct Template Reference
visioncpp::internal::EvalExpr< RDCN< C_OP, RHS, Cols, Rows, LfType, LVL >, Loc, Params...> Struct Template Reference
Partial specialisation of the EvalExpr when the expression is an RDCN(reduction operation) expression.
#include <eval_expr_reduction.hpp>
Static Public Member Functions
template<bool IsRoot, size_t Halo_Top, size_t Halo_Left, size_t Halo_Butt, size_t Halo_Right, size_t Offset, size_t Index, size_t LC, size_t LR>
static auto eval_neighbour (Loc &cOffset, const tools::tuple::Tuple< Params...> &t) -> decltype(tools::tuple::get< OutputLocation< IsRoot, Offset+Index-1 >::ID >(t))
evaluate function when the internal::ops_category is NeighbourOP.
template<bool IsRoot, size_t Offset, size_t Index, size_t LC, size_t LR>
static auto eval_global_neighbour (Loc &cOffset, const tools::tuple::Tuple< Params...> &t) -> decltype(tools::tuple::get< OutputLocation< IsRoot, Offset+Index-1 >::ID >(t))
Detailed Description
template<typename C_OP, typename RHS, size_t Cols, size_t Rows, size_t LfType, size_t LVL, typename Loc, typename... Params>
struct visioncpp::internal::EvalExpr< RDCN< C_OP, RHS, Cols, Rows, LfType, LVL >, Loc, Params...>
Partial specialisation of the EvalExpr when the expression is an RDCN(reduction operation) expression.
Definition at line 33 of file eval_expr_reduction.hpp.
Member Function Documentation
template<typename C_OP , typename RHS , size_t Cols, size_t Rows, size_t LfType, size_t LVL, typename Loc , typename... Params> template<bool IsRoot, size_t Offset, size_t Index, size_t LC, size_t LR> static auto visioncpp::internal::EvalExpr< RDCN< C_OP, RHS, Cols, Rows, LfType, LVL >, Loc, Params...>::eval_global_neighbour (Loc & cOffset, const tools::tuple::Tuple< Params...> & t) -> decltype(tools::tuple::get<OutputLocation<IsRoot, Offset + Index - 1>::ID>(t)) inline static
Definition at line 94 of file eval_expr_reduction.hpp.
References visioncpp::internal::calculate_index(), visioncpp::internal::tools::convert(), visioncpp::scope::Local, and visioncpp::internal::GlobalNeighbour< T >::set_offset().
template<typename C_OP , typename RHS , size_t Cols, size_t Rows, size_t LfType, size_t LVL, typename Loc , typename... Params> template<bool IsRoot, size_t Halo_Top, size_t Halo_Left, size_t Halo_Butt, size_t Halo_Right, size_t Offset, size_t Index, size_t LC, size_t LR> static auto visioncpp::internal::EvalExpr< RDCN< C_OP, RHS, Cols, Rows, LfType, LVL >, Loc, Params...>::eval_neighbour (Loc & cOffset, const tools::tuple::Tuple< Params...> & t) -> decltype(tools::tuple::get<OutputLocation<IsRoot, Offset + Index - 1>::ID>(t)) inline static
evaluate function when the internal::ops_category is NeighbourOP.
Definition at line 40 of file eval_expr_reduction.hpp.
References visioncpp::internal::calculate_index(), visioncpp::internal::tools::convert(), visioncpp::scope::Local, and visioncpp::internal::LocalNeighbour< T >::set_offset().
The documentation for this struct was generated from the following file:
eval_expr_reduction.hpp