VisionCpp: visioncpp::internal::EvalExpr< Assign< LHS, RHS, Cols, Rows, LfType, LVL >, Loc, Params... > Struct Template Reference
visioncpp::internal::EvalExpr< Assign< LHS, RHS, Cols, Rows, LfType, LVL >, Loc, Params... > Struct Template Reference
Partial specialisation of the EvalExpr when the expression is an Assign expression.
#include <eval_expr_assign.hpp>
Public Types
using LHS_Eval_Expr = EvalExpr< LHS, Loc, Params... >
using RHS_Eval_Expr = EvalExpr< RHS, Loc, Params... >
Static Public Member Functions
static auto get_accessor (const tools::tuple::Tuple< Params... > &t) -> decltype(LHS_Eval_Expr::get_accessor(t))
static auto eval_point (Loc &cOffset, const tools::tuple::Tuple< Params... > &t) -> typename MemoryTrait< LfType, decltype(LHS_Eval_Expr::get_accessor(t))>::Type
evaluate function when the internal::ops_category is PointOP.
template<bool IsRoot, size_t Halo_Top, size_t Halo_Left, size_t Halo_Butt, size_t Halo_Right, size_t Offset, size_t Index, size_t LC, size_t LR>
static auto eval_neighbour (Loc &cOffset, const tools::tuple::Tuple< Params... > &t) -> decltype(tools::tuple::get< OutputLocation< IsRoot, Offset+Index - 1 >::ID >(t))
evaluate function when the internal::ops_category is NeighbourOP.
template<bool IsRoot, size_t Offset, size_t Index, size_t LC, size_t LR>
static auto eval_global_neighbour (Loc &cOffset, const tools::tuple::Tuple< Params... > &t) -> decltype(tools::tuple::get< OutputLocation< IsRoot, Offset+Index - 1 >::ID >(t))
evaluate function when the internal::ops_category is GlobalNeighbour.
Detailed Description
template<typename LHS, typename RHS, size_t Cols, size_t Rows, size_t LfType, size_t LVL, typename Loc, typename... Params>
struct visioncpp::internal::EvalExpr< Assign< LHS, RHS, Cols, Rows, LfType, LVL >, Loc, Params... >
Partial specialisation of the EvalExpr when the expression is an Assign expression.
This node is not a root node.
Definition at line 33 of file eval_expr_assign.hpp.
Member Typedef Documentation
LHS_Eval_Expr
template<typename LHS , typename RHS , size_t Cols, size_t Rows, size_t LfType, size_t LVL, typename Loc , typename... Params> using visioncpp::internal::EvalExpr< Assign< LHS, RHS, Cols, Rows, LfType, LVL >, Loc, Params... >::LHS_Eval_Expr = EvalExpr<LHS, Loc, Params...>
Definition at line 34 of file eval_expr_assign.hpp.
RHS_Eval_Expr
template<typename LHS , typename RHS , size_t Cols, size_t Rows, size_t LfType, size_t LVL, typename Loc , typename... Params> using visioncpp::internal::EvalExpr< Assign< LHS, RHS, Cols, Rows, LfType, LVL >, Loc, Params... >::RHS_Eval_Expr = EvalExpr<RHS, Loc, Params...>
Definition at line 35 of file eval_expr_assign.hpp.
Member Function Documentation
eval_global_neighbour()
template<typename LHS , typename RHS , size_t Cols, size_t Rows, size_t LfType, size_t LVL, typename Loc , typename... Params> template<bool IsRoot, size_t Offset, size_t Index, size_t LC, size_t LR> static auto visioncpp::internal::EvalExpr< Assign< LHS, RHS, Cols, Rows, LfType, LVL >, Loc, Params... >::eval_global_neighbour (Loc & cOffset, const tools::tuple::Tuple< Params... > & t) -> decltype(tools::tuple::get<OutputLocation<IsRoot, Offset + Index - 1>::ID>(t)) inline static
evaluate function when the internal::ops_category is GlobalNeighbour.
Definition at line 106 of file eval_expr_assign.hpp.
References visioncpp::internal::calculate_index().
eval_neighbour()
template<typename LHS , typename RHS , size_t Cols, size_t Rows, size_t LfType, size_t LVL, typename Loc , typename... Params> template<bool IsRoot, size_t Halo_Top, size_t Halo_Left, size_t Halo_Butt, size_t Halo_Right, size_t Offset, size_t Index, size_t LC, size_t LR> static auto visioncpp::internal::EvalExpr< Assign< LHS, RHS, Cols, Rows, LfType, LVL >, Loc, Params... >::eval_neighbour (Loc & cOffset, const tools::tuple::Tuple< Params... > & t) -> decltype(tools::tuple::get<OutputLocation<IsRoot, Offset + Index - 1>::ID>(t)) inline static
evaluate function when the internal::ops_category is NeighbourOP.
Definition at line 52 of file eval_expr_assign.hpp.
References visioncpp::internal::calculate_index(), visioncpp::internal::tools::convert(), visioncpp::internal::tools::tuple::get(), and visioncpp::scope::Local.
eval_point()
template<typename LHS , typename RHS , size_t Cols, size_t Rows, size_t LfType, size_t LVL, typename Loc , typename... Params> static auto visioncpp::internal::EvalExpr< Assign< LHS, RHS, Cols, Rows, LfType, LVL >, Loc, Params... >::eval_point (Loc & cOffset, const tools::tuple::Tuple< Params... > & t) -> typename MemoryTrait<LfType, decltype(LHS_Eval_Expr::get_accessor(t))>::Type inline static
evaluate function when the internal::ops_category is PointOP.
Definition at line 41 of file eval_expr_assign.hpp.
get_accessor()
template<typename LHS , typename RHS , size_t Cols, size_t Rows, size_t LfType, size_t LVL, typename Loc , typename... Params> static auto visioncpp::internal::EvalExpr< Assign< LHS, RHS, Cols, Rows, LfType, LVL >, Loc, Params... >::get_accessor (const tools::tuple::Tuple< Params... > & t) -> decltype(LHS_Eval_Expr::get_accessor(t)) inline static
Definition at line 36 of file eval_expr_assign.hpp.
The documentation for this struct was generated from the following file:
eval_expr_assign.hpp