VisionCpp: visioncpp::internal::EvalExpr< LeafNode< PlaceHolder< Memory_Type, N, Cols, Rows, Sc >, LVL >, Loc, Params... > Struct Template Reference
visioncpp::internal::EvalExpr< LeafNode< PlaceHolder< Memory_Type, N, Cols, Rows, Sc >, LVL >, Loc, Params... > Struct Template Reference
Partial specialisation of the EvalExpr when the expression is an LeafNode expression and the internal::ops_category is NeighbourOP.
#include <eval_expr_leaf_node.hpp>
Public Types
using Expr = LeafNode< PlaceHolder< Memory_Type, N, Cols, Rows, Sc >, LVL >
Static Public Member Functions
static auto get_accessor (const tools::tuple::Tuple< Params... > &t) -> decltype(tools::tuple::get< N >(t))
static auto eval_point (Loc &cOffset, const tools::tuple::Tuple< Params... > &t) -> decltype(tools::tuple::get< N >(t) .get_pointer()[cOffset.pointOp_gc+(Cols *cOffset.pointOp_gr)])
evaluate function when the internal::ops_category is PointOP.
template<bool IsRoot, size_t Halo_Top, size_t Halo_Left, size_t Halo_Butt, size_t Halo_Right, size_t Offset, size_t Index, size_t LC, size_t LR>
static auto eval_neighbour (Loc &cOffset, const tools::tuple::Tuple< Params... > &t) -> decltype(tools::tuple::get< Index_Finder< N, OutputLocation< IsRoot, Offset+Index - 1 >::ID, Memory_Type, Trait< typename tools::RemoveAll< decltype(tools::tuple::get< N >(t))>::Type >::scope >::Index >(t))
evaluate function when the internal::ops_category is NeighbourOP.
template<bool IsRoot, size_t Offset, size_t Index, size_t LC, size_t LR>
static auto eval_global_neighbour (Loc &, const tools::tuple::Tuple< Params... > &t) -> decltype(tools::tuple::get< N >(t))
evaluate function when the internal::ops_category is GlobalNeighbour;
Detailed Description
template<size_t Memory_Type, size_t N, size_t Cols, size_t Rows, size_t LVL, size_t Sc, typename Loc, typename... Params>
struct visioncpp::internal::EvalExpr< LeafNode< PlaceHolder< Memory_Type, N, Cols, Rows, Sc >, LVL >, Loc, Params... >
Partial specialisation of the EvalExpr when the expression is an LeafNode expression and the internal::ops_category is NeighbourOP.
Definition at line 33 of file eval_expr_leaf_node.hpp.
Member Typedef Documentation
Expr
template<size_t Memory_Type, size_t N, size_t Cols, size_t Rows, size_t LVL, size_t Sc, typename Loc , typename... Params> using visioncpp::internal::EvalExpr< LeafNode< PlaceHolder< Memory_Type, N, Cols, Rows, Sc >, LVL >, Loc, Params... >::Expr = LeafNode<PlaceHolder<Memory_Type, N, Cols, Rows, Sc>, LVL>
Definition at line 35 of file eval_expr_leaf_node.hpp.
Member Function Documentation
eval_global_neighbour()
template<size_t Memory_Type, size_t N, size_t Cols, size_t Rows, size_t LVL, size_t Sc, typename Loc , typename... Params> template<bool IsRoot, size_t Offset, size_t Index, size_t LC, size_t LR> static auto visioncpp::internal::EvalExpr< LeafNode< PlaceHolder< Memory_Type, N, Cols, Rows, Sc >, LVL >, Loc, Params... >::eval_global_neighbour (Loc & , const tools::tuple::Tuple< Params... > & t) -> decltype(tools::tuple::get<N>(t)) inline static
evaluate function when the internal::ops_category is GlobalNeighbour;
Definition at line 73 of file eval_expr_leaf_node.hpp.
eval_neighbour()
template<size_t Memory_Type, size_t N, size_t Cols, size_t Rows, size_t LVL, size_t Sc, typename Loc , typename... Params> template<bool IsRoot, size_t Halo_Top, size_t Halo_Left, size_t Halo_Butt, size_t Halo_Right, size_t Offset, size_t Index, size_t LC, size_t LR> static auto visioncpp::internal::EvalExpr< LeafNode< PlaceHolder< Memory_Type, N, Cols, Rows, Sc >, LVL >, Loc, Params... >::eval_neighbour (Loc & cOffset, const tools::tuple::Tuple< Params... > & t) -> decltype(tools::tuple::get<Index_Finder< N, OutputLocation<IsRoot, Offset + Index - 1>::ID, Memory_Type, Trait<typename tools::RemoveAll<decltype(tools::tuple::get<N>(t))>::Type>::scope>::Index>(t)) inline static
evaluate function when the internal::ops_category is NeighbourOP.
Definition at line 53 of file eval_expr_leaf_node.hpp.
References visioncpp::internal::fill_local_neighbour(), and visioncpp::internal::tools::tuple::get().
eval_point()
template<size_t Memory_Type, size_t N, size_t Cols, size_t Rows, size_t LVL, size_t Sc, typename Loc , typename... Params> static auto visioncpp::internal::EvalExpr< LeafNode< PlaceHolder< Memory_Type, N, Cols, Rows, Sc >, LVL >, Loc, Params... >::eval_point (Loc & cOffset, const tools::tuple::Tuple< Params... > & t) -> decltype(tools::tuple::get<N>(t) .get_pointer()[cOffset.pointOp_gc + (Cols * cOffset.pointOp_gr)]) inline static
evaluate function when the internal::ops_category is PointOP.
Definition at line 43 of file eval_expr_leaf_node.hpp.
References visioncpp::internal::calculate_index().
get_accessor()
template<size_t Memory_Type, size_t N, size_t Cols, size_t Rows, size_t LVL, size_t Sc, typename Loc , typename... Params> static auto visioncpp::internal::EvalExpr< LeafNode< PlaceHolder< Memory_Type, N, Cols, Rows, Sc >, LVL >, Loc, Params... >::get_accessor (const tools::tuple::Tuple< Params... > & t) -> decltype(tools::tuple::get<N>(t)) inline static
Definition at line 37 of file eval_expr_leaf_node.hpp.
The documentation for this struct was generated from the following file:
eval_expr_leaf_node.hpp